#!/usr/bin/env php
<?php

use Arrilot\BitrixDataAnonymization\Database as BitrixDatabase;
use Arrilot\DataAnonymization\Anonymizer;
use Arrilot\DataAnonymization\Blueprint;

define("NOT_CHECK_PERMISSIONS", true);
$_SERVER["DOCUMENT_ROOT"] = __DIR__;
require $_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php";

Blueprint::setDefaultPrimary('ID');

$anonymizer = new Anonymizer(new BitrixDatabase());

$anonymizer->table('b_user', function (Blueprint $table) {
    $table->column('login')->where('ID != 1')->replaceWith('email_#row#@example.com');
    $table->column('email')->where('ID != 1')->replaceWith('email_#row#@example.com');
});

$anonymizer->run();

echo 'Anonymization has been completed!';